[package]
name = "forum-api-rust"
version = "0.1.0"
authors = ["captain328 <captainsuper328@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
